server:
  port: 8081

#Database Configuration
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Eh202036
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-25531855.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client-credentials
            scope: internal
            clientId: 0oabreorpww21PGwx5d7
            clientSecret: _GEsoihQKSZ6y5b4CCyep9YRnnfN8cyIpWPG-XKgYXJFNrOuchxdUfz71nadPm4Z
        provider:
          okta:
            issuerUri: https://dev-25531855.okta.com/oauth2/default

#eureka:
#  instance:
#   prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#Circuit breaker configurations
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 3s
        limit-for-period: 5
        timeout-duration: 0s
okta:
  oauth2:
    issuer: https://dev-25531855.okta.com/oauth2/default
    audience: api://default

